---
title: "Beta diversity"
---

```{r}
#libraries
library(phyloseq)
library(vegan)
library(dplyr)
library(ggplot2)
library(ggConvexHull) #devtools::install_github("cmartin/ggConvexHull")
library(reshape2)
library(ggh4x) # devtools::install_github("teunbrand/ggh4x")
library(ggpubr)
```

```{r}
# seed and pathways
set.seed(0201)
sessionInfo()
filepath = "/R_Analysis_MMS-FTS"
filepath_results =paste0( "/R_Analysis_MMS-FTS/results/", Sys.Date(), "_")
filepath_figures = paste0("/R_Analysis_MMS-FTS/figures/" , Sys.Date(), "_")
source(paste0(filepath, "/functions/plot.settings.R"))
source(paste0(filepath, "/functions/min.mean.sd.max.R"))
```

```{r}
#attach data set
exp_nor = readRDS(file = paste0(filepath,"/results/2022-01-11_zOTU_dataset_scaled_rarified.rds") )
```


# All samples 
```{r}
dist = c("Bray_Curtis", "Sørensen", "UniFrac", "W_UniFrac")
plotlist = vector("list", length = 4) #make a list with the length of the dist string
names(plotlist) = dist #renames the list

physeq = exp_nor 

#Bray
ordination_bray = phyloseq::ordinate(physeq = physeq, method = "PCoA", distance = "bray") 
plotlist$Bray_Curtis$ordination = ordination_bray
plot_bray = phyloseq::plot_ordination(physeq = physeq, ordination = ordination_bray, 
                                      title = "Bray-Curtis",  axes = c(1,2))
plotlist$Bray_Curtis$plot = plot_bray

#Sørensen has to be calculated with the vegan package
OTU_table = t(as.matrix(physeq@otu_table@.Data) ) 
sorensen = vegan::vegdist(OTU_table, method = "bray", binary = TRUE) #binary as true makes it Sørensen. 
ordination_sor = phyloseq::ordinate(physeq = physeq, method = "PCoA", distance = sorensen)
plot_sor = phyloseq::plot_ordination(physeq = physeq, ordination = ordination_sor, 
                                   title = "Sørensen", axes = c(1,2)) 
#adds the sorensen as a component to the plotlis
plotlist$Sørensen$ordination = ordination_sor
plotlist$Sørensen$plot = plot_sor

#UniFrac
ordination_uni = phyloseq::ordinate(physeq = physeq, method = "PCoA", distance = "unifrac") 
plotlist$UniFrac$ordination = ordination_uni
plot_uni = phyloseq::plot_ordination(physeq = physeq, ordination = ordination_uni, 
                                      title = "UniFrac (unweighted)",  axes = c(1,2))
plotlist$UniFrac$plot = plot_uni

#Weighted unifrac
ordination_wuni = phyloseq::ordinate(physeq = physeq, method = "PCoA", distance = "wunifrac") 
plotlist$W_UniFrac$ordination = ordination_wuni
plot_wuni = phyloseq::plot_ordination(physeq = physeq, ordination = ordination_wuni, 
                                      title = "UniFrac (weighted)",  axes = c(1,2))
plotlist$W_UniFrac$plot = plot_wuni

saveRDS(object = plotlist, file = paste0(filepath_results, "PCoA_ordination_plots.RDS"))
```

BrayCurtis
```{r}
bcplot = plotlist$Bray_Curtis$plot + my.theme
bcplot$layers = bcplot$layers[-1] #removes points in plot

bcplot = bcplot +  
  #ggConvexHull::geom_convexhull(alpha = 0.3, aes(fill = interaction(DPH, Current_system)))  +
  theme(panel.border = element_rect(fill = NA), 
        text = element_text(size = 12), 
        legend.position = "bottom") +

  geom_point(size = 3, aes(shape = as.character(DPH) , fill = Overall_system), color = "black") + 
  geom_point(size = 2.5,  aes(color = Overall_system, shape = as.character(DPH) )) + 
  geom_point(color = "black", fill = NA, size = 3, aes(shape = as.character(DPH) )) + 
  
  scale_color_manual("Overall_system",  values = system_overall_color) + 
  scale_fill_manual("Overall_system",values = system_overall_fill) + 
  scale_shape_manual("DPH",values = system_shape_day) + 
  guides(colour = guide_legend(override.aes = list(shape = 21, linetype = rep(0,8) ) )) + 
  coord_fixed(ratio = 20.8/39.2) +
  ggtitle(element_blank())

bcplot
```

Weighted unifrac
```{r}
wuni_plot = plotlist$W_UniFrac$plot + my.theme
wuni_plot$layers = wuni_plot$layers[-1] #removes points in plot

wuni_plot = wuni_plot +  
  #ggConvexHull::geom_convexhull(alpha = 0.3, aes(fill = interaction(DPH, Current_system)))  +
  theme(panel.border = element_rect(fill = NA), 
        text = element_text(size = 12), 
        legend.position = "right") +

  geom_point(size = 3, aes(shape = as.character(DPH) , fill = Overall_system), color = "black") + 
  geom_point(size = 2.5,  aes(color = Overall_system, shape = as.character(DPH) )) + 
  geom_point(color = "black", fill = NA, size = 3, aes(shape = as.character(DPH) )) + 
  
  scale_color_manual("Overall_system",  values = system_overall_color) + 
  scale_fill_manual("Overall_system",values = system_overall_fill) + 
  scale_shape_manual("DPH",values = system_shape_day) + 
  guides(colour = guide_legend(override.aes = list(shape = 21, linetype = rep(0,8) ) )) +
    coord_fixed(ratio = 19.8/53.9) + 
  theme(plot.margin=unit(c(-0.40,0,-0.4,0), "null")) + 
   ggtitle(element_blank())
wuni_plot
```


```{r}
ggarrange(bcplot, wuni_plot , legend = "right", common.legend = TRUE, ncol = 1)

ggsave(filename = paste0(filepath_figures, "PCoA_all-samples-bc_wuni.svg"), width = 180, height = 100, units = "mm")
```

# Only 12 DPH 
```{r}
dist = c("Bray_Curtis", "Sørensen", "UniFrac", "W_UniFrac")
plotlist = vector("list", length = 4) #make a list with the length of the dist string
names(plotlist) = dist #renames the list

physeq = phyloseq::subset_samples(exp_nor, DPH == 12)

#Bray
ordination_bray = phyloseq::ordinate(physeq = physeq, method = "PCoA", distance = "bray") 
plotlist$Bray_Curtis$ordination = ordination_bray
plot_bray = phyloseq::plot_ordination(physeq = physeq, ordination = ordination_bray, 
                                      title = "Bray-Curtis",  axes = c(1,2))
plotlist$Bray_Curtis$plot = plot_bray

#Sørensen has to be calculated with the vegan package
OTU_table = t(as.matrix(physeq@otu_table@.Data) ) 
sorensen = vegan::vegdist(OTU_table, method = "bray", binary = TRUE) #binary as true makes it Sørensen. 
ordination_sor = phyloseq::ordinate(physeq = physeq, method = "PCoA", distance = sorensen)
plot_sor = phyloseq::plot_ordination(physeq = physeq, ordination = ordination_sor, 
                                   title = "Sørensen", axes = c(1,2)) 
#adds the sorensen as a component to the plotlis
plotlist$Sørensen$ordination = ordination_sor
plotlist$Sørensen$plot = plot_sor

#UniFrac
ordination_uni = phyloseq::ordinate(physeq = physeq, method = "PCoA", distance = "unifrac") 
plotlist$UniFrac$ordination = ordination_uni
plot_uni = phyloseq::plot_ordination(physeq = physeq, ordination = ordination_uni, 
                                      title = "UniFrac (unweighted)",  axes = c(1,2))
plotlist$UniFrac$plot = plot_uni

#Weighted unifrac
ordination_wuni = phyloseq::ordinate(physeq = physeq, method = "PCoA", distance = "wunifrac") 
plotlist$W_UniFrac$ordination = ordination_wuni
plot_wuni = phyloseq::plot_ordination(physeq = physeq, ordination = ordination_wuni, 
                                      title = "UniFrac (weighted)",  axes = c(1,2))
plotlist$W_UniFrac$plot = plot_wuni

saveRDS(object = plotlist, file = paste0(filepath_results, "PCoA_ordination_plots_day12.RDS"))
```

BrayCurtis
```{r}
bcplot = plotlist$Bray_Curtis$plot + my.theme
bcplot$layers = bcplot$layers[-1] #removes points in plot

bcplot = bcplot +  
  ggConvexHull::geom_convexhull(alpha = 0.3, aes(fill = Current_system))  +
  theme(panel.border = element_rect(fill = NA), 
        text = element_text(size = 10), 
        legend.position = "right") +

  geom_point(size = 3, aes(fill = Overall_system), color = "black", shape = 21) + 
  geom_point(size = 2.5,  aes(color = Overall_system), shape = 21 )   + 
  geom_point(color = "black", fill = NA, size = 3, shape = 21)  + 
  
  scale_color_manual("Rearing condition", values = system_overall_color) + 
  scale_fill_manual("Rearing condition", values = system_overall_fill) + 
  guides(colour = guide_legend(override.aes = list(shape = 21, linetype = rep(0,8) )) )  + 
  coord_fixed(ratio = 16.4/46.4) + 
  ggtitle(element_blank())

bcplot
ggsave(bcplot, filename = paste0(filepath_figures, "PCoA_all-samples-bc_day12.svg"), width = 180, height = 100, units = "mm")
```

Weighted unifrac
```{r}
wuni_plot = plotlist$W_UniFrac$plot + my.theme
wuni_plot$layers = wuni_plot$layers[-1] #removes points in plot

wuni_plot = wuni_plot +  
  ggConvexHull::geom_convexhull(alpha = 0.3, aes(fill = Current_system))  +
  theme(panel.border = element_rect(fill = NA), 
        text = element_text(size = 10), 
        legend.position = "right") +

  geom_point(size = 3, aes(fill = Overall_system), color = "black", shape = 21) + 
  geom_point(size = 2.5,  aes(color = Overall_system), shape = 21 )   + 
  geom_point(color = "black", fill = NA, size = 3, shape = 21)  + 
  
  scale_color_manual("Overall system", values = system_overall_color) + 
  scale_fill_manual("Overall system", values = system_overall_fill) + 
  guides(colour = guide_legend(override.aes = list(shape = 21, linetype = rep(0,8) ) )) +
    coord_fixed(ratio = 19.7/55.3)

```

```{r}
ggarrange(bcplot, wuni_plot , legend = "right", common.legend = TRUE, ncol = 1)

ggsave(filename = paste0(filepath_figures, "PCoA_all-samples-bc_wuni_day12.svg"), width = 180, height = 100, units = "mm")
```

# Quantifying beta diveristy values
```{r}
physeq = exp_nor
distance = phyloseq::distance(physeq = physeq, method = "bray", type = "samples")
dist_matrix = as.matrix(distance)
dist_matrix[upper.tri(dist_matrix)] <- NA
distance_df = melt(dist_matrix, varnames = c("Sample_A", "Sample_B"))
distance_df$value = 1-distance_df$value #converts to similarity
colnames(distance_df)[3] = "BrayCurtis_sim"
distance_df = na.omit(distance_df)

col_keep = c("Sample", "DPH","Tank","Start_system","Current_system","Overall_system", "cc" , "cc_s")
metaA = data.frame(sample_data(physeq)) %>% select(col_keep)
colnames(metaA) = paste0(colnames(metaA), "_A") 
metaA = metaA %>% mutate(switched_A = case_when(Start_system_A == Current_system_A ~ "no", 
                                      TRUE ~ "yes"))
metaB = data.frame(sample_data(physeq)) %>% select(col_keep)
colnames(metaB) = paste0(colnames(metaB), "_B") 
metaB = metaB %>% mutate(switched_B = case_when(Start_system_B == Current_system_B ~ "no", 
                                      TRUE ~ "yes"))

distance_df_a = merge(distance_df, metaA, by = "Sample_A")
distance_df_both = merge(distance_df_a, metaB, by = "Sample_B")
saveRDS(object = distance_df_both, file = paste0(filepath_results, "bray-curtis-values-between-all-samples.RDS"))
```

```{r}
distance_df_both = readRDS(file = paste0(filepath, "/results/2022-01-14_bray-curtis-values-between-all-samples.RDS")) 
source(paste0(filepath, "/functions/plot.settings.R"))
dist_day_comp =distance_df_both %>% 
  filter(Sample_A != Sample_B, 
         Start_system_A == Start_system_B) %>%
  mutate(day_comp = paste0("DPH: ", DPH_A, " vs ", DPH_B)) %>% 
  mutate(day_comp = case_when(day_comp == "DPH: 12 vs 1" ~ "DPH: 1 vs 12", 
                              TRUE ~ day_comp)) %>% 
  filter(case_when(day_comp == "DPH: 1 vs 1" ~ Current_system_A == Current_system_B, 
                   day_comp == "DPH: 12 vs 12" ~ Current_system_A == Current_system_B, 
                   day_comp == "DPH: 1 vs 12" ~ Sample_A == Sample_A) ) %>%
  mutate(switch = paste0(switched_A, " vs ", switched_B)) %>%
  mutate(switch = case_when(switch == "no vs yes" ~ "yes vs no", 
                              TRUE ~ switch), 
         comp = case_when(switch == "no vs no" ~ Overall_system_A, 
                          switch == "yes vs yes" ~ Overall_system_A, 
                          switch == "yes vs no" ~ paste0(Overall_system_A, " vs ", Overall_system_B) ) ) %>% 
  mutate(comp = case_when(comp == "FTS- to MMS- vs FTS-" ~ "FTS- vs FTS- to MMS-", 
                          comp == "FTS+ to MMS+ vs FTS+" ~ "FTS+ vs FTS+ to MMS+", 
                          comp == "MMS- to FTS- vs MMS-" ~ "MMS- vs MMS- to FTS-", 
                          comp == "MMS+ to FTS+ vs MMS+" ~ "MMS+ vs MMS+ to FTS+",
                              TRUE ~ comp), 
         comp_plot = case_when(comp == "FTS- vs FTS- to MMS-"~ "FTS- to MMS-", 
                          comp == "FTS+ vs FTS+ to MMS+"~ "FTS+ to MMS+", 
                          comp == "MMS- vs MMS- to FTS-"~ "MMS- to FTS-", 
                          comp == "MMS+ vs MMS+ to FTS+" ~ "MMS+ to FTS+", 
                              TRUE ~ comp) ) 
dist_day_comp = dist_day_comp %>% mutate(switched = case_when(switch == "no vs no" ~ "no", 
                          switch == "yes vs yes" ~ "no", 
                          switch == "yes vs no" ~ "yes"))

dist_day_plot = dist_day_comp %>% 
  ggplot2::ggplot(aes(x=Start_system_A, y = BrayCurtis_sim)) + 
  facet_grid(~day_comp) +
  my.theme + 
  scale_color_manual("Overall_system", values = system_overall_color) + 
  scale_fill_manual("Overall_system",values = system_overall_fill) + 
  scale_shape_manual(values = c(22,23)) +
  
  geom_point(size = 4, aes(fill = comp_plot, shape = switched), color = "black") + 
  geom_point(size = 3.5, aes(color = comp_plot, shape = switched) ) + 
  geom_point(color = "black", fill = NA, size = 4, aes(shape = switched)) + 
  xlab("Start system") + 
  ylab("Bray Curtis similarity") + 
  theme(text = element_text(size = 12))


ggsave(dist_day_plot, filename = paste0(filepath_figures, "bc-sim_same_start.svg"), width = 180, height = 60, units = "mm")
```

```{r}
dist_day_comp %>% filter(day_comp == "DPH: 1 vs 12") %>% group_by(Start_system_A) %>%
  summarise(mean_BC = round(mean(BrayCurtis_sim), 3), n= n())


dist_day_comp %>% filter(day_comp == "DPH: 1 vs 12") %>% group_by(comp) %>%
  summarise(mean_BC = round(mean(BrayCurtis_sim), 3), n= n())
```

#Anova 1 vs 12 dph BC
```{r}
between_days_bc  = dist_day_comp %>% filter(day_comp == "DPH: 1 vs 12") %>% group_by(Start_system_A) %>%
  select(day_comp, Start_system_A,Overall_system_A, Start_system_B,Overall_system_B, BrayCurtis_sim )

between_days_bc 

fligner.test(data = between_days_bc, BrayCurtis_sim ~ Start_system_A) #sig
shapiro.test(between_days_bc$BrayCurtis_sim) # sig

kruskal.test(BrayCurtis_sim ~ Start_system_A, data = between_days_bc)


res.aov.1.12 = aov(Diversity_number ~ cc, data = between_days_bc)
# Summary of the analysis
summary(res.aov.1.12) # p 6.83e-06
```
