---
title: "Survival main tanks"
---

```{r}
#libraries
library(dplyr)
library(ggplot2)
library(readxl)
```

```{r}
# seed and pathways
set.seed(0201)
sessionInfo()
filepath = "/R_Analysis_MMS-FTS"
filepath_results =paste0( "/R_Analysis_MMS-FTS/results/", Sys.Date(), "_")
filepath_figures = paste0("/R_Analysis_MMS-FTS/figures/" , Sys.Date(), "_")
source(paste0(filepath, "/functions/plot.settings.R"))
source(paste0(filepath, "/functions/min.mean.sd.max.R"))
```

```{r}
#attach data set
survival = readxl::read_excel(paste0(filepath, "/data/2021-06-28_All_results.xlsx"), 
                             sheet = "survival_maintank")
```

```{r}
tank_groups = readxl::read_excel(paste0(filepath, "/data/2021-06-28_All_results.xlsx"), 
                             sheet = "tank_selection")
tank_groups = tank_groups %>% mutate(System_start = substr(Overall_system, start = 1, stop = 4) ) 
```

```{r}
survival.1 = merge(survival, tank_groups)
survival.2 = survival.1 %>% mutate(survival = round(Survival_n_larvea*100/(100*100),1) )  
avg.survival = survival.2 %>% group_by(Overall_system) %>% summarise(avg_sur = mean(survival)) %>% 
  mutate(sur_t = paste0(round(avg_sur,0), "%"))
survival.3 = merge(survival.2, avg.survival)
```


```{r}
survival.3 %>% 
  ggplot2::ggplot(aes(x = Overall_system, y =survival )) + 
  facet_grid(~System_start, scales = "free_x") + 
  
  my.theme + 
  scale_color_manual("Rearing condition",  values = system_overall_color) + 
  scale_fill_manual("Rearing condition",values = system_overall_fill) + 
  scale_shape_manual("Rearing condition",values = system_overall_shape21) +  
  guides(colour = guide_legend(override.aes = list(shape = 21)), 
         shape = guide_legend(nrow = 2)) + 
  
  stat_summary(fun.y=mean, geom="bar", fill = "grey90", color = "black") +
  stat_summary(fun.y=mean, geom="text", aes(label=paste0(sprintf("%1.0f", ..y..),"%")), 
               size=4, show.legend=FALSE,   hjust = 1, vjust= -1 ) +

  geom_point(size = 3, 
             aes(shape = Overall_system, fill = Overall_system), color = "black") + 
  
  geom_point(size = 2.5,  
             aes(color = Overall_system, shape = Overall_system)) + 
  
  geom_point(color = "black", fill = NA, size = 3, 
             aes(shape = Overall_system)) +
  
    theme(legend.position = "none") + 

  coord_cartesian(expand = TRUE) + 
  xlab("") + 
  ylab("Survival (%)") + 
  theme(text = element_text(size = 14)) + 
  theme(axis.text.x = element_text(size = 9))

ggsave(filename = paste0(filepath_figures, "final_survival_bar.svg"), width = 180, height = 80, units = "mm")
```

```{r}
saveRDS(object = survival.3, file = paste0(filepath_results, "survival.RDS"))
```

